autotest/virt-test

virttest/qemu_vm.py
when reboot a linux guest  with a serial_login session, test will failed as "guest refuse to reboot", 
root cause is we judge guest begin to reboot via checking serial not responsible.  
=> virttest.qemu_vm: make reboot work for linux serial session

shared/unattended/Ubuntu-12-04.preseed, shared/unattended/Ubuntu-14-04.preseed
In system_set_bootable test, recordfail set to 1 when reset guest before guest boot into OS, and make_timeout function in /etc/grub.d/00_header will set timeout to -1 if GRUB_RECORDFAIL_TIMEOUT not set. And grub wait  user to select boot OS. Now set GRUB_RECORDFAIL_TIMEOUT and update grub before finished install to fix this issue.
=> shared.unattended: fix ubuntu timeout lost issue

virttest/qemu_qtree.py
Corrently the image name will include two quotations in the string.
And this will failed the parse. So remove the quotations to make
it work as expect.
=> virttest.qemu_qtree: Remove the quotations in image name

virttest/utils_libguestfs.py
For some Linux release(RHEL7.1), characters will have color
when we enter guestfish shell session. It may cause failure
of testcases. So covering it during testing.
Signed-off-by: Yu Mingfei <yumingfei@cn.fujitsu.com>
=> utils_libguestfs: Unset color environment for guestfish test.

virttest/utils_libguestfs.py
@yumingfei Sorry, i haven't check your PR carefully, unset command shouldn't execute by utils.run, this function will fork a subprocess to run your command which will have no effect on current process and subprocess we created later like guestfish.
=> Fix bc4bfb8, run unset under the same process for guestfish

virttest/iscsi.py, virttest/iscsi_unittest.py
Get rid of exception if iscsiadm command fails to excute
during iscsi cleanup process.
=> virttest.iscsi: Ignore status for iscsiadm.

virttest/libvirt_xml/accessors.py, virttest/libvirt_xml/devices/disk.py, virttest/libvirt_xml/devices/seclabel.py, virttest/utils_test/libvirt.py
As libvirt xml support per-disk seclabel setting, implement seclabel class which include multiple element texts and attributes.
Handle the element texts in marshal_from_seclabel and XMLElementList, update both to handle extra dict under key 'text'.
e.g.
There are text element 'label' and 'baselabel' in seclabel:
```
<source path='/tmp/file'>
<seclabel model='dac' relabel='no'>
<label>0:0</label>
<baselabel>0:0</baselabel>
</seclabel>
</source>
```
both text element under parent tag 'seclabel' and with text value.
the return tuple of marshal_from_seclabel will be:
```
('seclabel', {'text': {'label': '0:0', 'baselabel': '0:0'}, 'model': 'dac', 'relabel': 'yes'})
```
and XMLElementList will create child element text after create seclabel element with attribute.
This update is different to …
=> Add per-disk seclabel support

virttest/libvirt_vm.py
Using a deterministic log file name will cause overwrite of serial
log and only the last serial log file will be saved if multiple
log session has been established in one test.
This patch add a random suffix to prevent overwrite.
=> virttest.libvirt_vm: Generate random serial log file name

virttest/utils_test/libvirt.py
1. Use kwargs instead of optional parameters
2. Support 'source-format' when prepare pool
3. Support both ipv4 and ipv6 for iscsi pool
4. Support define persistent pool
5. Update SCSI pool XML create method
=>     utils_test.libvirt: Update prepare pool method

shared/cfg/guest-os/Linux/CentOS.cfg, shared/cfg/guest-os/Linux/CentOS/7.0.cfg, shared/cfg/guest-os/Linux/CentOS/7.0/x86_64.cfg, shared/downloads/centos70-64.ini, shared/unattended/CentOS-7-0.ks
Added CentOS 7.0 x86_64 guest to virt-test infrastructure, it is based on RHEL 7.0 x86_64 guest configuration.
=> Add CentOS 7.0 support

virttest/utils_test/__init__.py
Although the docstring of class VMStress metioned iozone,
in fact, it doesn't support increase workload using iozone tool.
This patch make it into practice.
=> utils_test.__init__.py: make class VMStress support iozone tool

virttest/utils_misc.py
As it may take a long time to install packages, need a parameter to
specify timeout value.
=> utils_misc: Add timeout parameter to yum_install.

virttest/qemu_vm.py
Fix nic_index miss when reboot with session=None.
ID:1183987
=> virt.virttest.qemu_vm: reboot with passed nic when session is None

virttest/libvirt_vm.py, virttest/libvirt_xml/vm_xml.py, virttest/utils_test/libvirt.py
Guest agent is vastly used in the tests so a single function call
to prepare guest agent is needed. Current using method set_guest_agent()
in virttest.util_test.libvirt is not so flexible. For example for tests
requiring a guest with agent channel but no agent service etc.
In this patch we implemented a method prepare_guest_agent() in libvirt_vm
class to setup guest agent as required for guest.
Major changes including:
1)  Changes get_agent_channels() and remove_agent_channels() from
static method back to normal method since using static method
is not straightforward. There are many misuses of static method
in libvirt_xml module and We should change them later since
code dependence is tangled.
2)  Besides the prepare_guest_agent() method mentioned above, two new
methods install_package() …
=> virttest: Refactorize guest agent related functions

virttest/utils_test/libvirt.py
This helper function is an enhanced version to existing function
check_exit_status().
The original one only tests whether the exit status matches expectation.
The newer one also consider the content of the error messages if the
command is expected be fail.
Add expected fail patterns (regex) as a list for expected_fails
argument.  If test stderr matches non of these, an TestFail will emit.
If this list is empty. Command is expected to be successful. If the
command is expected be fail but the error pattern does not matter,
setting any_error to True will suffice.
If any of the skip_if list of regex matches command stderr. The test
will skip.
=> virttest.utils_test.libvirt: Add helper function to check command result

virttest/libvirt_xml/devices/interface.py
Libvirt support apply filter rules to specific interface by adding
filterref xml in domain interface, add new Filterref class under
Interface class to support set and get interface filterref rules.
About filterref xml with variables, check reference:
http://libvirt.org/formatnwfilter.html#nwfconceptsvars
=> libvirt_xml.devices.interface: Add filterref xml class

virttest/remote.py
The last of the function should be moved outside of the while loop.
Otherwise it will never be executed.
=> virttest: Fix the wrong indent in handle_prompts

virttest/utils_net.py
Some tests need the command line execution results.
=> virttest: Make openflow_manager can return results

virttest/libvirt_xml/devices/console.py, virttest/libvirt_xml/devices/serial.py
This patch add 'protocol_type', 'target_port', 'target_type' and 'sources' elements to console 
device XML and 'target_port', 'target_type' and 'sources' elements to console device XML.
=> Fill missing XML elements for console and serial devices

virttest/libvirt_xml/accessors.py, virttest/libvirt_xml/vm_xml.py, virttest/remote.py
Please refer to commit messages for the reasoning.
=> Fix typo error and add a new helper function remove_all_device_by_type

virttest/qemu_qtree.py
Current output of qtree will include hex numbers and this makes
the transfer from string to int failed. So remove it to make the function
works as expect.
=> virttest: Update check_guests_proc_scsi in qemu_qtree

virttest/iscsi.py
The old regex can only match node incomplete ipv6 address(eg. ::1),
after update it, it can match all ipv6 address.
And, when delete iscsi node, afte match the expected target, and delete
it, jump the loop immediately.
=> virttest.iscsi: Correct the regex to get all ipv6 version nodes

virttest/libvirt_vm.py
add_serial() method returned None in case VM lacks --serial option, it caused concatenation error in make_create_command() method.
=> Bug fix: libvirt_vm.py in add_serial() method

virttest/utils_test/libvirt.py
Currently tgtadm may be not work on RHEL7,
because they are using an interactive tool named targetcli.
So it's necessary to sidestep it when tgtadm does not work
and iscsi moduld does not support it.
Signed-off-by: Yu Mingfei <yumingfei@cn.fujitsu.com>
=> utils_test.libvirt: Support tester-defined device

virttest/libvirt_xml/vm_xml.py
For support guest numa config, add memnode element under numatune
and cell element under cpu.
More info please check:
http://libvirt.org/formatdomain.html#elementsNUMATuning
http://libvirt.org/formatdomain.html#elementsCPU
=> libvirt_xml.vm_xml: Add guest numa memory and cell config element

virttest/utils_test/libvirt.py
This PEP8 error is merged because this PR is checked as pass
on Travis CI before W503 is introduced in pep8.
=> utils_test.libvirt: Fix PEP8 W503

virttest/utils_test/libvirt.py
Extract the common that used to create channel xml file
in tp-libvirt, and regard it as a common funciton
=> utils_test.libvirt: add function create_channel_xml

virttest/tests/unattended_install.py
Serial log file name has been changed with a random suffix in commit
b2a48d5, but the reference to this log file in unattended install has
not changed accordingly.
This patch fix this problem and remove an unnecessary check of serial
ports since this is already on in vm.create_serial_console()
=> unattended_install: Change serial log name accordingly

virttest/openvswitch.py
With this, we'll be able to handle versions like
2.3.1-git3282e51 correctly.
=> client.shared.openvswitch: Fix version parsing

virttest/utils_net.py
This is a simple fix for:
```
16:10:23 ERROR| Traceback (most recent call last):
16:10:23 ERROR|   File "/home/virt-test/virttest/standalone_test.py", line 220, in run_once
16:10:23 ERROR|     run_func(self, params, env)
16:10:23 ERROR|   File "/usr/lib/python2.7/site-packages/autotest/client/shared/error.py", line 141, in new_fn
16:10:23 ERROR|     return fn(*args, **kwargs)
16:10:23 ERROR|   File "/home/virt-test/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/boot.py", line 25, in run
16:10:23 ERROR|     session = vm.wait_for_login(timeout=timeout)
16:10:23 ERROR|   File "/home/virt-test/virttest/virt_vm.py", line 1022, in wait_for_login
16:10:23 ERROR|     username, password)
16:10:23 ERROR|   File "/usr/lib/python2.7/site-packages/autotest/client/shared/error.py", …
```
=> virttest.utils_net: Use correct module for wait_for

virttest/qemu_vm.py
The command sent to qemu monitor for RHEL7 host 
during migration of RHEL6 guests was incorrect. 
"__com.redhat_spice_migrate_info", "spice_migrate_info" 
and "client_migrate_info" are the commands sent to 
qemu monitor during migration. While running on
RHEL7 host, the first 2 commands are coming up
as not supported and "client_migrate_info" is the 
command that is sent and the command is
framed incorrectly for RHEL7. 
Reviewed By: Swapna Krishnan <skrishna@redhat.com>
=> virttest.qemu_vm: Fix migration for RHEL7 host

run, virttest/bootstrap.py, virttest/standalone_test.py, virttest/tests/unattended_install.py
This reverts the commit 93b821d and adds @ldoktor's 'Change logic of download_image and restore_image'. Both were necessary for me to successfully install JeOS 21 using `virt-test`.
=> Unattended fixes 2015-03-03

shared/unattended/CentOS-7-0.ks
Enable dhclient on boot for eth0 network interface.
=> CentOS 7.0: Fix kickstart file for unattended install

virttest/libvirt_vm.py
=> virttest/libvirt_vm: fix typo

virttest/libvirt_xml/vm_xml.py
The commit e310f272f9 introduces this problem.
The error message as following,
AttributeError: 'VMCPUXML' object has no attribute 'mashal_to_cell'
=> libvirt_xml.vm_xml: fix typo that leads to attribute error

shared/cfg/machines.cfg, shared/unattended/CentOS-7-0.ks, shared/unattended/Fedora-10.ks, shared/unattended/Fedora-11.ks, shared/unattended/Fedora-12.ks, shared/unattended/Fedora-13.ks, shared/unattended/Fedora-14.ks, shared/unattended/Fedora-15.ks, shared/unattended/Fedora-16.ks, shared/unattended/Fedora-17.ks, shared/unattended/Fedora-18.ks, shared/unattended/Fedora-19.ks, shared/unattended/Fedora-20.ks, shared/unattended/Fedora-8.ks, shared/unattended/Fedora-9.ks, shared/unattended/Fedora-test.ks, shared/unattended/JeOS-19.ks, shared/unattended/JeOS-20.ks, shared/unattended/RHEL-3-series.ks, shared/unattended/RHEL-4-series.ks, shared/unattended/RHEL-5-series.ks, shared/unattended/RHEL-6-series.ks, shared/unattended/RHEL-6-spice.ks, shared/unattended/RHEL-6.3.ks, shared/unattended/RHEL-7-series.ks, virttest/bootstrap.py
Hi guys,
this pull request contains various fixes to support PPC64 out of the box. Please read the descriptions of each commits. I tested it on PPC running RH7, using RH7 images and kickstarts, but all of them should work fine.
Kind regards,
Lukáš
=> Couple of modifications to make PPC64 work out of the box

virttest/utils_test/__init__.py
Now we only can set one value to transfer_type. It is meaningless,
So just delete this parameter.
id: 1186122
=> virt.utils_test: Delete meaningless transfer_type parameter

virttest/env_process.py, virttest/utils_test/libvirt.py
Inactive pool checking added to get_all_vol_paths() function.
Minor fix in logging outpout in preprocess() function
=> utils_test.libvirt: skip inactive pools in get_all_vol_paths

virttest/virsh.py
Including: domstats, cpu-models, freepages, domcapabilities, metadata,
net-dhcp-leases, qemu-monitor-event, net-event, event.
=> virsh: Add new virsh commands

virttest/env_process.py
when test.iteration great than 1 screendump overwrite in same folder.
ID:1134194
=> virt-test.virttest.env_process: fix screendump overwirte issue

virttest/env_process.py
fix rescan, reconvert screendump and recreate video issue when test
iteration is great than 1. And recorrect ppm file directory in steps
for convertting and removing ppm files.
=> virt.virttest.env_process: fix duplicate ation in make screendump media

virttest/utils_test/libvirt.py
The VG creation failure with error 'incorrect metadata area header checksum'
occurred during multiple test runs. The solution is to call 'vgscan --cache'
in order to rebuild the LVM cache after the disk was deleted at the end of
the test
=> libvirt.py: Fixed the bug related to VG recreation failure (moved to setup_or_cleanup_iscsi())

virttest/libvirt_xml/devices/graphics.py, virttest/libvirt_xml/snapshot_xml.py, virttest/libvirt_xml/vm_xml.py, virttest/xml_utils.py
Original implementation of remove_by_xpath() only remove the first
occurrence of found elements. This leads to some misunderstanding and
misuse of this function.
This patch adds an option remove_all to make it able to remove all
found elements but retains the default to remove just once.
=> virttest.libvirt_xml: Fix misuse of remove_by_xpath

virttest/utils_misc.py
The system_output return string, while map need output to be list
of output lines.
=> utils_misc: Fix get_cpu_info when without session

virttest/utils_test/libvirt.py
As lvmetad could not running, the vgscan will fail, do not raise
error and fail then.
=> utils_test.libvirt: Ignore vgscan failure

virttest/utils_test/libguestfs.py
check is compulsory, otherwise,
it will report the following in same cases,
OSError: [Errno 2] No such file or directory
=> utils_test/libguestfs: check if file exists before removing

virttest/utils_libguestfs.py
The c51a2b2 introduces a bug,
which leads program would never enter 'else' block.
So, even if we specify option '-i',
it still report the following error message,
libguestfs:
error: umount_all: call launch before using this function
(in guestfish, don't forget to use the 'run' command)
=> virttest/utils_libguestfs: fix bug for guestfish

virttest/utils_spice.py
For spice tests on RHEL7, adding EPEL support for RHEL7
and restarting gdm in RHEL7 is required. 
Reviewed By: Swapna Krishnan <skrishna@redhat.com>
=> virttest.utils_spice: Add support for RHEL7

virttest/libvirt_vm.py, virttest/libvirt_xml/capability_xml.py, virttest/libvirt_xml_unittest.py
1. Update the function to get guest wordsize, emulator, machine and
domain that the host supported
2. Also rename the function to get_guest_capabilities()
=> capability_xml: Update get_os_arch_machine_map() to return more info

virttest/utils_net.py, virttest/virt_vm.py
A check for filtering incomplete ARP entries (flag 0x0) is added
into parse_arp(). Without this check the returned dictionary may
contain invalid (incomplete) IP addresses after parsing /proc/net/arp
virt_vm get_address() now will try to get the correct IP address
of the guest from the current ARP table in case if the DHCP assigned a
new address to guest after it's reboot, and the address_cache contains
old entries (additional check condition is added into the if-block).
An unnecessary checking loop is deleted.
=> utils_net , virt_vm: Finding correct guest IP using also ARP lookup

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices_unittest.py
qemu -device ? will fail if there is a single
char file in the cwd.
Triggered by running a command with 2&>1 which
generated a file named '1' in the cwd.
This caused us to call 'qemu -device 1' which
fails.
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
=> escape '?' wildcard when querying qemu devices

shared/cfg/base.cfg, virttest/env_process.py, virttest/qemu_vm.py
We have many thread need send monitor command. So Add a
catch_monitor for ScreenDump and VmRegister threads to reduce
acquire exclusive lock fail.
=> virt: Add catch_monitor for ScreenDump and VmRegister threads.

shared/cfg/base.cfg, virttest/libvirt_vm.py
This adds support for creating VM with memballoon device using virt-install
=> Libvirt: Add memballoon support for vm create

virttest/utils_test/__init__.py
import of submodules are mistakenly removed as unused import in 95509f0a94aea9d60dd726a6e0de30dcfcf2f251.
And a unused import of utils_cgroup is removed.
=> utils_test: Revert a mistakenly removed import

virttest/cartesian_config.py
Newest pylint remove the rule W0142
(https://bitbucket.org/logilab/pylint/commits/b6fbdc48d643a764bba1d47da87610ccbfb7555e)
This commit remove the original pylint disable line to make it
accord with the new rule and silence the CI error.
=> cartesian_config: Pylint W0142 no longer need disable

shared/cfg/guest-os/Linux/RHEL/7.devel.cfg, shared/cfg/guest-os/Linux/RHEL/7.devel/aarch64.cfg, shared/cfg/guest-os/Linux/RHEL/7.devel/ppc64.cfg, shared/cfg/guest-os/Linux/RHEL/7.devel/x86_64.cfg
This patch adds RHEL.7.devel variant which takes whatever
isos/linux/RHEL7-devel-{x86_64,ppc64,aarch64}.iso image exists and uses
it to install RHEL7-like OS. It's suitable to developers who need to use
the latest versions.
=> shared.cfg.guest_os: Add RHEL.7.devel variant

virttest/qemu_qtree.py
As the newest version of qemu-kvm updated the info qtree output for
virtio block device. So we need update the function to fit it.
=> virttest: Update the method of guess_type for QtreeDev

run, virttest/bootstrap.py, virttest/defaults.py, virttest/standalone_test.py
Hi guys,
this patchset unifies the `defaults.DEFAULT_GUEST_OS` and most importantly (to me) allows running virt-test on systems without `7za`. (so far I'd been using `touch /usr/local/7za` to workaround it, but it really is not a nice solution)
@lmr, @ypu would you please verify I'm not crucially wrong about the `defaults`? I grepped for all `defaults.DEFAULT...` and `defaults.get_default...` occurrences and IMO this solution reflects the usage properly.
regards,
Lukáš
=> virttest: Unify defaults.DEFAULT_GUEST_OS and avoid running without 7za

shared/cfg/guest-os/Linux/RHEL/7.devel/aarch64.cfg
Current RHEL.7.devel installation takes about 70-90 minutes right now.
Default timeout is 80min, which generates lots of false-negatives. This
patch increases the timeout to 120 minutes, which should be safe.
=> shared.cfg: Increase RHEL.7.devel install_timeout on aarch64

documentation/source/extra/DownloadableImages.rst
While passing for the docs, I've noticed that the links
to JeOS are outdated. Let's fix this.
=> docs/DownloadableImages.rst: Update JeOS download info

shared/cfg/guest-os/Linux/RHEL/7.devel.cfg, shared/unattended/RHEL-7-spice.ks
For SPICE testing, we needed a kickstart file with extra packages
and setup to be done. Also, modified 7.devel.cfg file to point to
RHEL-7-spice.ks.
Reviewed By: Swapna Krishnan <skrishna@redhat.com>
=> shared: Add RHEL-7-spice.ks and use for 7.devel testing

virttest/utils_test/libvirt.py
We have exec_edit() in virt_edit test case, it should be a common utility, so move it to virttest/utils_test/libvirt.py.
=> virttest.utils_test.libvirt: add exec_edit() as common utility

virttest/virsh.py
1. For --set option, the value should be quoted, so unity all single
quote to double quotes.
2. Fix a wrong variable
=> virsh: Correct metadata --set option

virttest/utils_netperf.py
=> virttest.utils_netperf: Increase netperf setup timeout.

virttest/staging/service.py
New method statuslog() is added. It is needed for getting the status log
text of the service. The existing status() method returns only the status
if the service runs or not
=> service.py: Added new method statuslog() to show the service status text

virttest/utils_test/__init__.py
Sometime the different setup in guest and host will cause the timestamp
in the future when we extract auotest package inside guest when we
try to run autotest inside guest. As this is not the test point and we
don't want this to influence our testing, add the option m to the tar
command to ignore this.
=> virttest.utils_test: Add option m to the tar command

shared/unattended/RHEL-6-spice.ks
Autotest generates a random mac address for the nic device. Udev rules
will generate a new interface for each "new" device when guest boots
up. So the nic interface changes and this confuses the network manager
inside guest which leads to system will not get "new" interface get IP
address automatically.
To avoid this, we comment out the rule being created with each boot.
This will allow the device to get IP address automatically.
Reviewed By: Swapna Krishnan <skrishna@redhat.com>
=> shared.unattended: Updating RHEL-6-spice.ks for RHEL 6.7

shared/cfg/guest-os/Linux/RHEL.cfg, shared/cfg/guest-os/Linux/RHEL/7.0/ppc64.cfg, shared/cfg/guest-os/Linux/RHEL/7.devel/aarch64.cfg, shared/cfg/guest-os/Linux/RHEL/7.devel/ppc64.cfg, shared/unattended/CentOS-7-0.ks, shared/unattended/RHEL-7-series.ks, shared/unattended/RHEL-7-spice.ks, virttest/tests/unattended_install.py
Hi guys,
this pull request contains 2 changes. First one is a bugfix found by @swapnakrishnan2k and it sets graphical or text installation based on "vga" param.
The second is RHEL kickstart refactor and minor issue fix.
Regards,
Lukáš
=> shared.cfg.guest_os: Cleanup and fixups in RHEL kickstarts

virttest/tests/unattended_install.py
arch was added by accident and is not used.
=> virttest.tests.unattended_install: Remove unused import

shared/cfg/guest-os/Linux/RHEL.cfg
This reverts one change made on 04350d9718 to unify kernel params
for RHEL versions.
Apparently RHEL6 x86 anaconda doesn't like ks=cdrom:sr1:/ks.cfg and
can't find the kickstart anymore. I can't really leave the x86 case
broken, so I'll have to revert this particular change. The change
was tested and reported to work on RHEL7 x86.
CC: Lukas Doktor <ldoktor@redhat.com>
=> shared/cfg/guest-os/Linux/RHEL.cfg: Revert change from 04350d9718

virttest/arch.py
Currently there was no support for ppc64le. This was causing issues with tun device on PowerKVM LE host mainly while running tests in qemu. Now this patch introduces arch support for ppc64le in addition to ppc64
=> Added support for ppc64le arch

virttest/test_setup.py
Sleep 3 sec is not enough sometimes,
It's necessary to ensure all of pids end up before follow-up steps.
=> virttest/test_setup: make sure all pids killed

virttest/libvirt_xml/nodedev_xml.py, virttest/utils_test/libvirt.py
1) libvirt_xml/nodedev_xml: Add virt_functions in PCIXML class.
This function had been reverted to fix conflicts.
But it's useful and needed by pci-passthrough cases.
so i modified it and pushed it again.
Refer to commit e1152a766ef46e092634d8 for more details.
2)utils_test/libvirt: using try/except to deal with KeyError
=> two commits about pci passthrough

virttest/qemu_devices/qcontainer.py
The image format is mandatory in the latest qemu but in virt-test it's only
set in strict_mode. This patch enables it in non-strict mode too.
=> virttest.qemu_devices: Image format is mandatory now

virttest/test_setup.py, virttest/utils_misc.py, virttest/utils_net.py
library function os.path.exists() will return True if
path refers to an existing path. Otherwise, return False.
in other words,
no boolean conditional statements for os.path.exists() is OK.
=> virttest: return os.path.exists()'s result directly

virttest/nfs.py
It's not safe that call shutil.rmtree to delete dir on NFS,
which maybe suffer from error 39 (directory not empty).
Please refer to the docstring of safe_rmdir for details.
=> virttest/nfs: replace shutil.rmtree with safe_rmdir

virttest/libvirt_vm.py
Just check the status is not safe,
although the status is zero, but package is not installed.
for example,
the ouput of session.cmd_status_output() as follow,
03:18:59 DEBUG| Sending command: rpm -q qemu-guest-agent ||
yum install -y qemu-guest-agent
03:18:59 DEBUG| Sending command: echo $?
(0, 'rpm -q qemu-guest-agent || yum install -y
qemu-guest-agen<qemu-guest-agent || yum install -y qemu-guest-agent
\x08\0x08\0x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\npackage
qemu-guest-agent is not installed\n
Loaded plugins: product-id, security, subscription-manager\n
This system is not registered to Red Hat Subscription
Management. You can use subscription-manager to register.\n
Setting up Install Process\n
No package qemu-guest-agent available.\nNothing to do\n')
so it's necessary to run …
=> virttest/libvirt_vm: check if install package successfully

virttest/qemu_devices/qcontainer.py, virttest/qemu_vm.py
Now we can set x-data-plane in following two ways:
iothreads = "iothread1 iotherad2"
iothread1_id = id_iothread1
x-data-plane = id_iothread1
Set x-data-plane to id of iothread1, will create command:
-object iothread,id=id_iothread1
-device virtio-blk-pci,id=image1,drive=drive_image1,bootindex=0,iothread=id_iothread1,bus=pci.0,addr=04
images += " disk1"
image_name_disk1 = images/storage
image_size_disk1 = 10G
x-data-plane_disk1 = yes
In rhel6 we only support x-data-plane = on/off. Set x-data-plane to yes,
will create command:
-device virtio-blk-pci,id=disk1,drive=drive_disk1,bootindex=1,x-data-plane=on,bus=pci.0,addr=05
=> virttest: Support iothread in qemu command

virttest/utils_misc.py
Just compare the return value of utils.run() with
expectation and return True or False directly.
No need to do it by means of if-block statements.
=> utils_misc: simplify codes for operating PCI

virttest/arch.py, virttest/qemu_devices/qcontainer.py, virttest/qemu_qtree.py, virttest/qemu_vm.py, virttest/utils_misc.py
The first patch is related to `-cpu` defaults, which are not exactly optimal (inspired by: https://github.com/autotest/virt-test/pull/2131#issuecomment-93384466 )
The second adds checks for `ppc64le` wherever we check for `ppc64`.
I tested this on Power8 running RHEL7.1, unattended_install works fine without -cpu using `le` host os.
=> virttest: Improve the ppc64le support

shared/control/parallel_dd.control
There are two changes:
- Test fs type are get from guest os
- Use oflag/iflag is direct for fs w/r test
=> shared.control: Update the parallel_dd to fit our test request

shared/cfg/guest-os/Linux/SLES/12.0.x86_64.cfg
In SLES.12, iso is called "/dev/sr*" now instead of
the old name "/dev/scd*", which is same as RHEL.7 now.
=> virt-test: some update for SLES.12 cfg.

virttest/utils_netperf.py
fixed that No return False for function is_target_running.
=> virttest/utils_netperf: fix no return False

virttest/virsh.py
Fix typo of --emulatorbin option.
=> virsh: fix typo in domcapabilities command

virttest/test_setup.py
* s/tansparent/transparent/g
* s/dealocate/deallocate/g
* s/seperated/separated/g
* s/satisify/satisfy/g
* s/assinged/assigned/g
* s/repalce/replace/g
* s/immidiately/immediately/g
=> virttest/test_setup: fix typo

shared/unattended/RHEL-7-spice.ks
Current setting requires eth called ens*. This patch forces the nic used
for installing the guest to be enabled and just to be sure enables all
defined nics to be enabled on boot.
=> shared.unattended.RHEL-7-spice: Make sure network is enabled

run, virttest/qemu_vm.py
The -nodefconfig parameter prevents QEMU from loading the
sysconfdir/qemu.conf and sysconfdir/target-ARCH.conf files at startup.
This patch adds support to virt-test add this parameter if specified by
user while launching virt-test.
Signed-off-by: Paulo Vital <paulo.vital@profitbricks.com>
=> Support to -nodefconfig into QEMU command line.

virttest/virsh.py
Both pool_define_as and pool_create_as needs to check
if the pool type is supported, and these codes are similar.
so extract the common part to reduce code redundancy.
=> virttest/virsh: extract common as a function

shared/unattended/RHEL-6-spice.ks, shared/unattended/RHEL-7-spice.ks
For spice testing, some new packages are required in the guest VMs.
Adding the packages pyparsing and python-six
Reviewed-By: Swapna Krishnan <skrishna@redhat.com>
=> shared.unattended: Add packages to RHEL-6-spice.ks and RHEL-7-spice.ks

virttest/qemu_vm.py
E126 means continuation line over-indented for hanging indent.
=> virttest/qemu_vm: fix pep8 E126

virttest/qemu_vm.py
As AMD do not support multi thread.
id: 1126299
=> virt.virttest.qemu_vm: Set vcpu_threads to 1 for AMD host

virttest/libvirt_storage.py
The function pool_delete() doesn't call virsh sub-command
pool-delete to delete a pool,
which looks without rhyme or reason.
This patch make some explanation for it.
=> virttest/libvirt_storage: elaborate on pool_delete

virttest/test_setup.py
It's better to check whether the system does support hugepages
function as same as the process for transparent hugepage.
This commit references the validating method in class libhugetlbfs
that declared at autotest/client/tests/libhugetlbfs/libhugetlbfs.py
=> virttest/test_setup: check if hugepages is supported

virttest/virsh.py
It's no need to store the result of command(cmd, **dargs)
as a variable and then return the variable.
=> virttest/virsh: return command() directly

virttest/libvirt_vm.py, virttest/virsh.py
The gracefully paramter hadn't been considered.
This PR fix it.
=> virttest: add option argument for virsh destroy

virttest/qemu_vm.py
If IndexError is raised,
The else-block statements never be run at graceful_shutdown().
Explanation As following,
try:
...
except (IndexError), e:
try:
session = self.serial_login()
except (remote.LoginError, virt_vm.VMError), e:
logging.debug(e)
>>>Although successfully get session by serial_login()
>>>The following else-block never be run.
except (remote.LoginError, virt_vm.VMError), e:
...
else:
>>>send shutdown command to VM if no error occurs.
This patch is dedicated to fix it.
=> virttest/qemu_vm: fix bug related to try-except-else

virttest/utils_libguestfs.py
copyonread is unavailable on old guestfish and
" copyonread:false" cause errors, such as following on RHEL6.7,
><fs> add-drive-opts /iso/g/images/rhel6X-64.qcow2 \
readonly:true copyonread:false
add-drive-opts: unknown optional argument "copyonread:false"
><fs>
And the default is false for copyonread,
so it's no need to set " copyonread:false" explicitly.
Please refer to manual for more details.
=> virttest/utils_libguestfs: No set copyonread explicitly

virttest/gluster.py
If glusterd keeps failed status after the first failure,
It would never be started as the orignal code.
In fact, If only the status of glusterd is not active,
we should try to start glusterd again for another cases.
=> virttest/gluster: fix bug for start glusterd

shared/unattended/SLES-12.xml
...ES 12
The old command will only update the line from no to yes. But in SLES 12 it still
start with '#' and the login in following cases will failed.
ID: 1218472
=> virttest.shared.unattended: Remove dhclient command from SLES 12

shared/unattended/SLES-10.xml
clean net udev rules and rename eth configuration to
make guest get ip address from dhcp server by default.
=> virt: update autoinstall.xml for sles10

virttest/env_process.py
1)  virttest/env_process: remove unused variables
The codes used to start tcpdump had been rewritten
into a new function called _start_tcpdump at utils_env.py.
But, It didn't discard unused variables by 4b518ed.
2)    virttest/env_process: fix exception string
If the exception has been logged by logging.error("e"),
Only one letter e will be output.
so replace "e" with str(e).
=> Two Commits for env_process.py

virttest/qemu_virtio_port.py
The socket.send can hang for infinity. Use timeout to ignore failed
write and re-try the virtconsole status afterwards. If sending the data
doesn't help VM gets destroyed.
=> virttest.qemu_virtio_port: Avoid infinity hang

.travis.yml
I ended up deleting the old packages, and haven't realized
that virt-test and tp-qemu still used them. Let's update
to the latest version available.
=> .travis.yml: Update autotest package to the newest version

virttest/qemu_vm.py
Arm doesn't support pci bus so instead virtio-serial-pci it has to use
virtio-serial-device.
=> virttest.qemu_vm: Support for virtio-serial-device on arm

virttest/data_dir.py
Current get_deps_dir() can not work under python 2.4 env as python have some bug in that version. So make a work around for it. And also update the function for checking deps dirs as deps is under shared in virt-test, the original check will never find it.
=> Two update for get_deps_dir in date_dir

virttest/qemu_virtio_port.py
ThSendCheck thread can hang when sending data to a full socket. Instead
of returning number of sent bytes python waits for infinity. Use
non-blocking send instead avoids this problem.
=> virttest.qemu_virtio_port: Avoid ThSendCheck thread hang

virttest/virsh.py
The commit d0d6610 introduced a new function named
_adu_device() and make it as the basis of
attach_device()/detach_device()/update_device().
But,
It forgot to remove unused statement in update_device().
cmd = "update-device".
=> virttest/virsh: cleanup code

run, virttest/bootstrap.py, virttest/standalone_test.py
The integration PR was cleaned up and updated. I'd like to get this into the consideration ASAP, please.
Changes from v3:
* Small tweak related to `~` inside $AUTOTEST_PATH
* Simplified a function's code in the added utility functions from runner script
* Use bootstrap.setup() inside `virt-test`.
Changes from v2:
* Dropped some refactored code from the test runner that is no longer useful
* Heavy cleanup on the interface of `bootstrap.bootstrap()`
* Add new interface `bootstrap.setup()`, that only concerns itself with setting up tests and mandates that users run the bootstrap procedure first.
Changes from v1:
* Dropped commits made obsolete by the latest version of the plugin
This contains some simple and not-so intrusive patches in order to support the virt test compatibility layer for …
=> [V4] Avocado integration

run
Fix issue introduced by commit 6ddc6783f9cd73b4deba94cb45df5b8ff16acc1c:
$ ./run -h
Traceback (most recent call last):
File "./run", line 976, in <module>
app = VirtTestApp()
File "./run", line 483, in __init__
self.system_setup()
File "./run", line 468, in system_setup
_import_autotest_modules()
File "./run", line 102, in _import_autotest_modules
autotest_dir = os.path.expanduser(os.environ.get('AUTOTEST_PATH'))
File "/usr/lib64/python2.7/posixpath.py", line 261, in expanduser
if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
=> run: Fix crash when $AUTOTEST_PATH is not set

virttest/utils_test/__init__.py
* remove unused list variable.
* return result of utils.system_output directly.
* remove meaningless statement.
=> virttest/utils_test/__init__.py:

virttest/qemu_devices/qcontainer.py, virttest/qemu_devices_unittest.py
Some new feature like dump-guest-core in qemu asks for command line
like '-machine pc,dump-guest-core=on/off', so we need let machine
type accepts extra parameters, and "-M" can not accept extra parameter
in qemu side, use "-machine".
ID: 1226116
Signed-off-by: Shaolong Hu <shu@redhat.com>
=> virt: enable machine_type accepts extra parameters

shared/scripts/virtio_console_guest.py
The variable name in AttributeError exception handling should be
line_list and not file.
=> shared.scripts.virtio_console_guest: Fix variable name

shared/cfg/guest-os/Linux/RHEL/7.devel/ppc64le.cfg
Tested on the latest RHEL7.1 available image.
=> cfg.guest-os: Add RHEL.7.devel.ppc64le variant

virttest/asset.py, virttest/bootstrap.py
Some guest OS naturally won't have assets associated with
them. Let's handle when that happens, in order to let people
run install tests on such guests.
=> virttest.bootstrap: setup() -> Handle guest OS that have no asset

shared/cfg/machines.cfg
Vga output was enabled in 121294e4ccd182eb46c4023771d177f2b5f1d690 lets
remove the screendump/inactivity_watcher sections to use defaults
instead.
=> cfg.machines: Don't disable screendump on PPC64

virttest/iscsi.py, virttest/iscsi_unittest.py, virttest/utils_test/libvirt.py
First :
utils_test/libvirt.py: fix call export_target() twice
If the parameter 'is_login' is true,
export_target() will be call two times.
Error message as following,
* Command:
targetcli /backstores/fileio/ create device.disk-pool
/mnt/extra_disk/osc /virt-test/tmp/disk-pool
Exit status: 1
Duration: 0.110117912292
stderr:
expected a character buffer object
so move the first export_target() to else-block.
Second:
virttest/iscsi.py: fix login failure
If both iSCSI server and iSCSI client are on localhost,
It's necessary to set up InitiatorName for localhost.
Otherwize, login will fail.
=> Fix two indetectable iscsi bug

virttest/utils_misc.py
The timeout passed is str type ,can will cause Type Error when i
execute a plus operation.
This patch is to modify timeout as float type.
BZ: 1241372
Signed-off-by: Mike Cao <bcao@redhat.com>
=> Fix the issue param 'timeout' to float type

virttest/service_unittest.py, virttest/staging/service.py
we should obey the rule that one function do one thing at a time,and do well.
so...
make it more tidy, readable and easier to understand.
modifications are mainly concentrated in the following,
* sys_v_init_result_parser
* systemd_result_parser
=> staging/service: refactor parser for sysvinit/systemd result

virttest/utils_test/libvirt.py
1. dir create in pre_pool sometimes duplicated with pool_build which may case error in new version,
so add 1 more condition for dir creat
2. before list volume, must make sure pool is active, else it will report error
=> Modify for pool problem fix

run, virttest/qemu_vm.py
The usage of "--sanbox=on/off" is dropped, we use
"qemu_sandbox=on/off" instead now.
Need update all the usage to "qemu_sandbox".
=> virt-test: qemu_vm.py: update the usage of option "qemu_sandbox".

shared/cfg/guest-hw.cfg
As virtio_blk does not have the interface for cdrom,
use "cd_format=ide" for virtio_blk.
id: 1238539
=> virt-test: guest-hw.cfg: set "cd_format=ide" for virtio_blk.

virttest/virsh.py
The old method for options in virsh blkdeviotune just fits
single option, but '--live --config' should be given at the same time.
=> Change the virsh blkdeviotune's options processing method.

shared/cfg/guest-os/Linux/Ubuntu/14.04.1-server.i386.cfg
Fix vm_arch_name configuration parameter for compatibility with kernel arch format
=> Ubuntu 14.04.01 Server i386 (libvirt backend)

shared/cfg/guest-os/Linux/Fedora/19.i386.cfg, shared/cfg/guest-os/Linux/Fedora/20.i386.cfg, shared/cfg/guest-os/Linux/RHEL/6.devel/i386.cfg, shared/cfg/guest-os/Linux/Ubuntu/12.04-server.i386.cfg, shared/cfg/guest-os/Linux/Ubuntu/14.04-server.i386.cfg
This fix required for compatibility with libvirt backend.
Arch name of 32-bit kernels for specified guests has i686 signature.
=> Fix vm_arch_name configuration parameter for various guests

virttest/libvirt_vm.py
In case of ESX protocol, virsh couldn't get MAC address of network adapter before VM was started.
=> libvirt: Get MAC address of remote VM after it was started

virttest/staging/utils_cgroup.py
No available libcgroup-tools introuces the following case fails.
resource_abnormal.virt_clone.normal_resource.twice_execute.kill_first
=> virttest/staging/utils_cgroup: check libcgroup-tools package

shared/cfg/guest-os/Linux/CentOS/7.0/x86_64.cfg, shared/downloads/centos70-64.ini, shared/unattended/CentOS-7-0.ks
1. Fix kickstart file for unattended install.
2. Replace DVD install media by minimal CD.
=> CentOS 7.0: Fix unattended install

virttest/utils_net.py
=> virttest.utils_net: Add missing parameter for class TAPModuleError()

shared/cfg/guest-os/Windows.cfg
When running multi_disk job ,we will hit "The process cannot access t he file because it is being used by another process" when trying to copy cmd.exe from D:\ to C:\
This patch is using notepad.exe to fix it.
ID: 1243345
Signed-off-by: Mike Cao <bcao@redhat.com>
=> using notepad.exe for copy insetead of cmd.exe

shared/cfg/machines.cfg, virttest/qemu_vm.py
=> virttest.qemu_vm: remove default parameter 'driftfix' for pseries

shared/unattended/Ubuntu-14-04-1.preseed, shared/unattended/Ubuntu-14-04.preseed
By default the root ssh login to Ubuntu 14.04 Linux
server is disable, need allow it.
=> shared.unattended: Allow ssh root login on Ubuntu 14.04 Linux server

virttest/virt_vm.py
The fef5c4c move mac_list() to the beginning of get_address(),
which leads to verification of arping result failed until
the timeout to zero.
The reason as following,
The self.virtnet of VM is created by VirtNet.__init__,
and the self.virtnet.mac isn't set any value.
So it's better to obtain the mac list after checking the
existence of this attribute by nic.has_key('mac').
=> virttest/virt_vm.py: Adjust timing to get mac list

backends/libguestfs/cfg/tests.cfg, backends/libvirt/cfg/tests.cfg, backends/openvswitch/cfg/tests.cfg, backends/qemu/cfg/tests.cfg, backends/v2v/cfg/tests.cfg, shared/cfg/guest-hw.cfg
display variants in commit 727ebae broken testing in ARM and PPC
testing, so remove this part of configuration.
=> virt-test: remove display configuration

virttest/virsh.py
In qemu_monitor_event() function, the parameter of timeout should be 
event_timeout, not event.
event() function has the same problem.
=> virttest.virsh: Bug fix for event()/qemu_monitor_event()

tools/build_docs.py, virttest/ovirt.py, virttest/ppm_utils.py, virttest/utils_env.py, virttest/utils_misc.py, virttest/utils_sasl.py, virttest/utils_v2v.py, virttest/virsh.py, virttest/virt_vm.py
Finally, the rewrite virt-v2v is ready for testing, so this patch
including 7 files update to make sure v2v test can work normally.
ovirt: Update for new ovirt API and bugs fix
ppm_utils.py: Introduce two functions for image crop and compare
utils_env: Update the tcpdump start function
utils_misc: Add a new function to add identities into ssh agent
utils_v2v: According the new version virt-v2v, update utils functions
and introduce a new VirshSession for SASL authentication(for
ovirt node virsh session creation)
virsh: Update VirshSession for inheritance and add two new functions for
mouse move and click.
virt_vm: Also get mac address from XML for v2v VM
=> v2v: Update the harness for new version virt-v2v testing

shared/cfg/guest-os/Linux.cfg, virttest/virt_vm.py
sometimes,  we got unprintable string in console output, convert a string to int will cause exception, so use regex to filter number string only.
=> virttest: small enhancement for get_cpu_count

virttest/iscsi.py
As multiple iscsi target could be created, use clearconfig to clear
entire local configuration will cause problem, so after each delete
use saveconfig will be safer.
=> iscsi: avoid aggressive clearconfig

virttest/iscsi.py, virttest/nfs.py, virttest/utils_net.py, virttest/utils_test/libvirt.py
In order to display message to users correctly,
The exception message has to use interpolation.
This PR refers to the commit beacb9d.
Signed-off-by: Wei,Jiangang <weijg.fnst@cn.fujitsu.com>
=> Fix skip message for TestFail()

virttest/utils_test/__init__.py
For some reason my autotest tarball was huge, so the md5sum
did not complete in the default timeout of 60 seconds
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
=> utils_test: increase timeout on md5sum since it can take a while

shared/cfg/guest-os/Linux/RHEL.cfg, virttest/qemu_vm.py
For old kernels (< 3.1), here is a console issue - if the very last
byte of the spapr-vty's "reg" property is not equal to zero, then it
will not appeared as 'hvc0' which is expected. So made a workaround
here to slove this problem. Details:
http://lists.gnu.org/archive/html/qemu-ppc/2013-10/msg00129.html
=> virttest.qemu_vm: add workaround for ppc console issue

virttest/utils_test/libvirt.py
Missed iothread option for disk paramters in set_vm_disk
=> virttest.utils_test.libvirt: Missed iothread option.

virttest/utils_test/__init__.py
If pbzip2 is detected, either with base_packages.has_pbzip2 or with
'which pbzip2' then use pbzip2 to compress.
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
=> utils_test: add pbzip2 support to tar

shared/cfg/guest-hw.cfg
e1000 & rtl8139 is not support in ppc 
this patch is to disable them on power platform
ID: 1247467
=> Disable ppc e1000

virttest/utils_v2v.py
Remove the '-f' option as it already discarded. And rename the variable
of input mode to avoid conflict with build-in function name.
=> utils_v2v: Remove the obsolete '-f' option

virttest/qemu_monitor.py
For booting up multiple vms, check monitor log is not really
easy, so add vm.name into it.
=> virttest.qemu_monitor: Add vm.name for monitor log

shared/cfg/guest-os/Windows/Win2008/i386.cfg, shared/cfg/guest-os/Windows/Win2008/x86_64.cfg, shared/cfg/guest-os/Windows/Win2012/x86_64.cfg, shared/cfg/guest-os/Windows/Win7/i386.cfg, shared/cfg/guest-os/Windows/Win7/x86_64.cfg, shared/cfg/guest-os/Windows/Win8/i386.cfg, shared/cfg/guest-os/Windows/Win8/x86_64.cfg, shared/cfg/virtio-win.cfg, shared/downloads/virtio-win.ini, virttest/tests/unattended_install.py
1. virtio-win.ini: Update URL.
2. virtio-win.cfg: Update paths for virtio-win-0.1-100.iso.
3. unattended_install.py: Prevent overwriting of self.cdrom_virtio attribute.
4. shared/cfg/guest-os/Windows: Fix virtio CD drive indexing in Windows guest config files.
Tested on Windows 2008 R2.
=> Fix virtio-win scheme

virttest/utils_test/__init__.py
For this case we had cached the tarball in the VM from a previous run, but we had removed the /usr/local/autotest directory to cleanup.
In this case we don't need a new tarball, we just need to extract the existing tarball if the directory doesn't exit.
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
=> utils_test: extract tarball when the remote dir not exist

virttest/qemu_storage.py
If backing_file is specified as "" (the empty string), then the
image is rebased onto no backing file
Signed-off-by: chendt.fnst <chendt.fnst@cn.fujitsu.com>
=> virttest.qemu_storage: Support -b "" for qemu_disk_img_rebase

shared/cfg/base.cfg
=> virt-test: base.cfg: set ehci as default usb controller in CML.
