- virttest/utils_test/__init__.py
Signed-off-by: Yang Xue <yaxue@redhat.com>
> Add te detail information of PING command to improve the debug log

- virttest/libvirt_vm.py
- virttest/qemu_vm.py
- virttest/virt_vm.py
add 'serial' params to support reboot via serial session.
> update reboot function in virt_vm

- virttest/libvirt_xml/devices/interface.py
> libvirt_xml.devices.interface: Add target tag

- virttest/virsh.py
> virttest.virsh: Add domfsfreeze, domfsthaw and domtime

- virttest/libvirt_vm.py
Add managedsave, pmsuspend, pmwakeup functions for libvirt_vm class
to ease these functions.
> virttest.libvirt_vm: Add managedsave, pmsuspend and pmwakeup

- virttest/utils_libguestfs.py
add command: mkmountpoint, readdir, mount_loop, rmmountpoint,, mount_vfs
> add command

- virt.py
- virttest/standalone_test.py
> virt: Run type script in a sequence defined by type parameter.

- virttest/utils_gdb.py
- virttest/utils_libvirtd.py
In this PR, a module utils_gdb for manipulating an inferior process in gdb is introduced.
Another commit in the PR brings a LibvirtdSession class which creates an interactive 
libvirt daemon session and can optionally use utils_gdb module debug the process.
These changes will be helpful to break at specific function call or get the backtrace info
etc.
> Introduce utils_gdb module and LibvirtdSession class

- virttest/utils_libguestfs.py
- virttest/utils_test/libguestfs.py
details are described in comments of commits
> add "utils" commands

- virttest/utils_libguestfs.py
virttest.utils_libguestfs.py: add functions belong to misc
> add functions belong to misc

- shared/cfg/guest-os/Linux/Ubuntu/14.04.1-server.i386.cfg
- shared/cfg/guest-os/Linux/Ubuntu/14.04.1-server.x86_64.cfg
- shared/downloads/ubuntu-14.04.1-server-32.ini
- shared/downloads/ubuntu-14.04.1-server-64.ini
- shared/unattended/Ubuntu-14-04-1.preseed
> Add support for Ubuntu Server 14.04.1 (i386, x86_64)

- virttest/libvirt_xml/nwfilter_xml.py
Multiple filterref could be in one filter, so update filterref use
XMLElementList and marshal functions to support this.
> libvirt_xml.nwfilter_xml: Use XMLElementList for filterref

- virttest/libvirt_xml/devices/graphics.py
> libvirt_xml.devices.graphics: add new attributes

- virttest/utils_test/libvirt.py
Create network filter xml use params from cfg file.
> utils_test.libvirt: Add create nwfilter xml function

- virttest/qemu_vm.py
> Fix issue in reboot

- shared/deps/run_autotest/boottool.py
- tools/regression.py
- virttest/cartesian_config.py
- virttest/env_process.py
- virttest/nfs.py
- virttest/nfs_unittest.py
- virttest/qemu_devices/qcontainer.py
- virttest/qemu_virtio_port.py
- virttest/qemu_vm.py
- virttest/staging/backports/collections/namedtuple.py
- virttest/staging/backports/simplejson/__init__.py
- virttest/staging/backports/simplejson/encoder.py
- virttest/staging/lv_utils.py
- virttest/standalone_test.py
- virttest/test_setup.py
- virttest/utils_misc.py
- virttest/utils_test/libvirt.py
- virttest/utils_test/qemu.py
The new pep8 adds W503 line break before %s check. This is mass style
update of autotest framework without any actual changes.
> PEP8 fixes

- virttest/utils_selinux.py
1) add option '-r' used to set MLS/MCS Security Range
for command semanage.
2) add option '-F' used to force a replacement of the entire context
for command restorecon.
> utils_selinux: add some useful options for setting selinux context

- virttest/libvirt_xml/capability_xml.py
Add TopologyXML and CellXML classes for handle host node cell
topology element in capabilities.
> libvirt_xml.capability_xml: Add classes handle cell topology

- shared/cfg/guest-os/Linux/RHEL/7.0/ppc64.cfg
- shared/unattended/RHEL-7-ppc-series.ks
Adding RHEL70 ppc64 guest os configuration file and kickstart file.
> Adding RHEL70 ppc64 guest os config and kickstart file

- shared/scripts/dd.py
- shared/scripts/telnet.py
These two scripts are used in openflow control test in windows guest.
> virt-test.shared.scripts: Add some scripts for openflow acl test

- virttest/libvirt_vm.py
add steps to check the status of qemu-guest-agent service
after starting or stopping it.
> virttest/libvirt_vm: check the status of qemu-guest-agent

- virttest/bootstrap.py
Modify bootstrap parameter for other script to use "force_update" to update config files in noninteractive mode.
> Add a parameter to bootstrap.

- virttest/libvirt_xml/devices/controller.py
> libvirt_xml.devices.controller: Add more attributes

- shared/cfg/guest-os/Windows.cfg
- shared/cfg/guest-os/Windows/Win2012.cfg
- virttest/utils_misc.py
Add the default value for mountpoint and size parameters.
> virttest.utils_misc: Update format_windows_disk function

- virttest/qemu_monitor.py
Make the code tidy and more easier to understand
> qemu_monitor: improves the logical order and readability

- virttest/qemu_virtio_port.py
- virttest/remote.py
- virttest/test_setup.py
- virttest/utils_test/__init__.py
- virttest/utils_test/qemu.py
> remove useless module imported

- shared/cfg/guest-os/Linux/RHEL/7.0/x86_64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1/x86_64.cfg
1. Add RHEL.7.1 guest config
2. Small update for RHEL.7.0 config
> shared.cfg.guest-os: Add RHEL.7.1 guest config

- virttest/utils_test/libvirt.py
> virttest.utils_test.libvirt: allow specific user to run virsh migrate command

- virttest/libvirt_vm.py
> virttest.libvirt_vm: don't hardcode swap path

- virttest/utils_test/libvirt.py
the hotplug/unhotplug operation can be supported by
setvcpus and qemu-monitor-command.
> utils_test.libvirt: add function to hotplug/unhotplug cpu

- virttest/utils_test/libvirt.py
> utils_test.libvirt: Add a function to generate vol name for disk pool

- virttest/libvirt_xml/devices/interface.py
> virttest.libvirt_xml.devices: update interface xml

- virttest/libvirt_xml/devices/smartcard.py
> virttest.libvirt_xml.devices: update smartcard xml

- virttest/libvirt_xml/devices/watchdog.py
> update watchdog xml

- virttest/utils_misc.py
Add new get cpu topology dict function, retrieve the cpu topology
info in certain node from sysfs.
Also fix get node cpus problem, the findall regex need match to
the end of line, and set extra_cpus from node 0 when current cpus
node not as 0.
> utils_misc: Add fuction get node cpu topology info

- virttest/libvirt_xml/devices/sound.py
> virttest.libvirt_xml.devices: update sound XML

- virttest/libvirt_xml/devices/interface.py
- virttest/libvirt_xml/network_xml.py
- virttest/utils_test/libvirt.py
Add more sections in xml to create_net_xml; 
add a parameter define_error for negative test.
> virttest.utils_test.libvirt: Update create_net_xml function.

- virttest/libvirt_xml/vm_xml.py
- virttest/utils_test/libvirt.py
The patch set is associated with the boot sequence of VM.
The VFIO cases will refer to them.
> Patch set for altering the Boot order 

- shared/deps/serial/VirtIoChannel_guest_send_receive.py
- shared/deps/serial/serial_host_send_receive.py
- shared/deps/serial/windows_support.py
- virttest/utils_test/__init__.py
> Virtio serial

- virttest/utils_conn.py
- virttest/virsh.py
- virttest/xml_utils.py
* s/manully/manually/g
* s/Forbide/Forbid/g
* s/varaibles/variables/g
> virttest: fix typo

- virttest/utils_test/__init__.py
The output from the commands have some slight change and caused the
function failed. So update the method to get time from related
commands.
> virt-test.virttest.utils_test: bug fix for get_time

- shared/cfg/guest-os/Linux/JeOS/21.x86_64.cfg
- shared/unattended/JeOS-21.ks
A few tweaks on our JeOS 21 image.
> Jeos 21 tweaks

- virttest/staging/service.py
For SysV case command generator is fixed in sys_v_init_command_generator()
> service.py: SysV command generator fix

- virttest/libvirt_vm.py
> libvirt_vm: Compatible qemu-guest-agent service for RHEL6&7

- virttest/utils_test/libvirt.py
TestNAError seems more reasonable.
> util_test/libvirt: raise TestNAError instead of TestError

- virttest/cartesian_config.py
- virttest/utils_spice.py
This patch does what is the same as commit de30fa4.
> virttest: the params of docstring should begin with colon

- virttest/gluster.py
* gluster_vol_stop: stop volume, not start
* gluster_vol_delete: delete the stopped volume, not start
> virttest/gluster: fix wrong docstring

- virttest/utils_netperf.py
use cmd_output_safe instead cmd_status_output to avoid output of
netperf client make netperf.is_target_running function failed when
netperf running in not quiet mode.
ID: 1198022
> virttest.utils_netperf: fix check netperf process

- virttest/utils_net.py
When host have multi network card in same subnet, guset may fail at
mac ip verify. Because code may ge a wrong device from ip route.
> virttest.utils_net: Try default route if selected route could not work.

- virttest/test_setup.py
- virttest/utils_config.py
Add function to get host supported page sizes, and functions get or
set per-node huge page size.
> test_setup: Add hugepage numa node functions

- virttest/utils_test/libvirt.py
> utils_test.libvirt: Support prepare persistent network

- virttest/qemu_vm.py
> virt-test: fix reboot issue on devel guest

- virttest/iscsi.py
- virttest/iscsi_unittest.py
- virttest/utils_test/libvirt.py
Add the new param in init and update libvirt iscsi config function to support use it.
> Add restart tgtd option in iscsi module

- virttest/utils_test/libvirt.py
Add check point to check the state of specific interface.
return True if state is active, otherwise return False.
> utils_test/libvirt: add check point for iface_check

- virttest/utils_virtio_port.py
> virttest.utils_virtio_port: Fix PEP8 complain

- virttest/utils_test/libvirt.py
> utils_test.libvirt: Add a function to update polkit rule

- shared/cfg/guest-os/Linux.cfg
- shared/cfg/guest-os/Windows.cfg
- virttest/utils_test/__init__.py
log debug info when no readable cdrom found
> virt.virttest: update function get_readable_cdroms

- shared/scripts/virtio_console_guest.py
- virttest/qemu_vm.py
- virttest/utils_test/qemu.py
Hello guys, this patchset contains various fixes found while working virtio_console test on secondary archs. Please read the details in each commit.
> virtio_console related fixes

- .travis.yml
> Updating the autotest used in the Travis environment

- virttest/env_process.py
- virttest/qemu_vm.py
- virttest/standalone_test.py
A couple trivial fixes found while working on the avocado compatibility layer plugin.
> Trivial fixes 2015 03 25

- virttest/libvirt_xml/nodedev_xml.py
The numa_node sys file could be with value -1, and no numa node
element in nodedev xml, it's handled with exception.
> nodedev_xml: Add pci numa node attribute

- virttest/qemu_devices/qcontainer.py
As spapr-vscsi is not a pci device, it should not be added to pci bus.
Also add the option bus for spapr-vscsi device as the default bus for
scsi-hd is virtio_scsi bus.
> virttest.qemu_devices: Update for spapr-vscsi device

- virttest/qemu_vm.py
1. update reboot keywords pattern
2. don't close session until search reboot keywords timeout
3. catch exception when it raise in  match keywords
> virt-test: fix bug in reboot function

- shared/unattended/SLES-12.xml
> virt-test: unattended: disable lock media rules in udev for SLES.12

- run
please look at it asap because it affect the test with run
> left 1 place change for avocado integration from lmr

- .gitignore
> .gitignore: Update with .idea intelliJ IDE dir

- backends/libguestfs/cfg/tests.cfg
- backends/libvirt/cfg/tests.cfg
- backends/openvswitch/cfg/tests.cfg
- backends/qemu/cfg/tests.cfg
- backends/v2v/cfg/tests.cfg
Add this filter for new added variants.
> backends: Add only default_bios to tests.cfg

- shared/cfg/guest-hw.cfg
> virt-test: guest-hw.cfg: specify cd_format for different drive_format.

- shared/cfg/guest-os/Linux/RHEL/7.1/ppc64.cfg
- shared/cfg/guest-os/Linux/RHEL/7.1/ppc64le.cfg
- shared/cfg/machines.cfg
> shared.cfg.machines: update pseries config

- backends/libguestfs/cfg/tests.cfg
- backends/libvirt/cfg/tests.cfg
- backends/openvswitch/cfg/tests.cfg
- backends/qemu/cfg/tests.cfg
- backends/v2v/cfg/tests.cfg
- shared/cfg/guest-hw.cfg
> virt-test: guest-hw.cfg: add variants for nettype.

- virttest/utils_test/libvirt.py
Add iscsi volume disk type in set_vm_disk, iscsi volume type require
define iscsi pool first for using the volume in vm.
Check more disk info in:
http://libvirt.org/formatdomain.html#elementsDisks
> utils_test.libvirt: Add iscsi volume disk type

- shared/cfg/base.cfg
- shared/cfg/guest-hw.cfg
- virttest/ceph.py
- virttest/env_process.py
- virttest/qemu_storage.py
- virttest/qemu_vm.py
- virttest/storage.py
Make guest can use ceph backends.
> virttest: Add support for ceph

- virttest/utils_env.py
- virttest/virt_vm.py
After fef5c4c5cd2da1b7509283f3b3db06166c4c8615 applied, not we need cleanup code for implement ip_pool.
thanks,
Xu
> Cleanup get IP address  releated function

- virttest/utils_test/__init__.py
The codes of get_free_space call self.runner.run twice,
and No catch IndexError/ValueError for the following,
int(line.split()[3]) / 1048576
Besides above, It's better to output the return of
self.runner.run for failure case, not for successful case.
and so on.
So need to rewirte and make it more better.
> utils_test/__init__.py: rewrite get_free_space()

- shared/cfg/guest-hw.cfg
> shared.cfg.guest-hw: disable ovmf for powerpc

- virttest/iscsi.py
> virt-test: iscsi.py: emulated_image only for emulational_iscsi

- backends/libguestfs/cfg/tests.cfg
- backends/libvirt/cfg/tests.cfg
- backends/openvswitch/cfg/tests.cfg
- backends/qemu/cfg/tests.cfg
- backends/v2v/cfg/tests.cfg
- shared/cfg/guest-hw.cfg
> Add iscsi nfs image backend and  display varinat support

- virttest/utils_test/qemu.py
> virttest.utils_test/.qemu: Add new class MultihostMigrationRdma

- backends/libvirt/cfg/drivers.cfg
- run
- virttest/libvirt_vm.py
> libvirt: Add basic support of ESX protocol

- virttest/libvirt_xml/pool_xml.py
Main modification as following,
* Remove the call for pool_destroy().
delete_pool() will destroy pool if it's active,
so no need to call pool_destroy() explicitly.
* Call uniform cleanup function while failure appears.
* No catch CmdError for pool_xml.define_pool.
because it will return True or False and
keep consistence with others.
> virttest/libvirt_xml/pool_xml: revise pool_rename

- shared/cfg/guest-os/Linux/CentOS/6.6.cfg
- shared/cfg/guest-os/Linux/CentOS/6.6/i386.cfg
- shared/cfg/guest-os/Linux/CentOS/6.6/x86_64.cfg
- shared/downloads/centos66-32.ini
- shared/downloads/centos66-64.ini
- shared/unattended/CentOS-6-6.ks
> Introduce CentOS 6.6 guest support (i386 and x86_64)

- virttest/utils_net.py
> virttest.utils_net: Add new function get_host_default_gateway()

- virttest/libvirt_storage.py
- virttest/libvirt_storage_unittest.py
- virttest/libvirt_xml/pool_xml.py
- virttest/libvirt_xml/secret_xml.py
- virttest/virsh.py
libvirt_storage, virsh: add rbd pool support; modify pool_define_as function to make target as the optional
disk, pool_xml, secret_xml: add some new rbd pool/volume attributes to xml.
> Rbd disk type support.

- virttest/iscsi.py
- virttest/utils_test/libvirt.py
Ipv6 portal address can'be created by default, we need to add a parameter
add then create ipv6 portal if needed.
> Provide portal_ip for iscsi setup.

- virttest/qemu_storage.py
- virttest/storage.py
> the QemuImg class doesn't have a params attribute, causing failures at postprocess

- shared/cfg/guest-os/Linux/RHEL/6.7.cfg
- shared/cfg/guest-os/Linux/RHEL/6.7/i386.cfg
- shared/cfg/guest-os/Linux/RHEL/6.7/x86_64.cfg
> virt-test: guest-os: Add RHEL.6.7 guest os config.

- virttest/utils_test/__init__.py
> virttest.utils_test: Small bug fix for get_time()

- virttest/iscsi.py
- virttest/utils_test/libvirt.py
Lun number is needed to build domain xml for iscsi disk, store
the lun number during iscsi setup and make it available to iscsi object.
> Return lun number in setup_or_cleanup_iscsi.

- shared/cfg/base.cfg
- virttest/qemu_vm.py
> virt: introduce add qemu options support

- shared/cfg/machines.cfg
- virttest/qemu_vm.py
> virt: qemu_vm support pvpanic device

- virttest/qemu_vm.py
> ignore exit status when check is pvpanic device supportted

- virttest/utils_test/qemu.py
1. Enable the windows driver verifier.
2. Verify the windows driver verifier.
3. Clear the windows driver verifier.
id: 1256248
> virt-test: utils_test.qemu: Add some func() for windows driver verifier.

- virttest/qemu_vm.py
> virttest.qemu_vm: Add function for disable-legacy and disable-modern

- virttest/qemu_vm.py
> virt-test: add check before add virtocosole device

- virttest/qemu_vm.py
Conflicts:
virttest/qemu_vm.py
> use exists function in framework to check pvpanic dev
